nelmio_cors:
    defaults:
        allow_origin: ['http://w2-groupe4.hetic-projects.arcplex.tech:8090'] # Remplacez par l'URL exacte de votre frontend
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/': ~
