version: '3'

services:
    frontend:
        build:
            context: ./docker/front
            dockerfile: Dockerfile
        container_name: front
        ports:
            - "88:80"
        volumes:
            - ./Frontend:/project

    back:
        build:
            context: ./docker/back
            dockerfile: Dockerfile
        container_name: back
        ports:
            - '4557:80'
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb'
        container_name: db
        ports:
            - '3307'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./Database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


    myadmin:
        image: phpmyadmin:latest
        environment:
            UPLOAD_LIMIT: 524288000
        ports:
            - "8081:80"
        container_name: myadmin


volumes:
    postgres15: